### ISSUE TITLE
Bug: Arc browser. 401 cors to /rpc/v3/scw/getAccounts

### ISSUE THREAD

**Issue by Yuripetusko** [coinbase/coinbase-wallet-sdk#1278]
### Describe the bug

When launching smart wallet in Arc browser, it opens it in a new tab, but it never loads. I see bunch of polled /rpc/v3/scw/getAccounts requests with 401 status

### Steps

1. Using latest rainbowkit, wagmi, and @coinbase/wallet-sdk: "4.0.0-beta.12"
2. Click a button to connect a wallet using coinbase connector
3. Arc browser opens a new tab for https://keys.coinbase.com/sign/eth-request-accounts and loading start but never finishes
4. console shows a bunch of polled requests to https://api.wallet.coinbase.com/rpc/v3/scw/getAccounts with status 401

Same code works in Brave browser

### Expected behavior

Smart wallet popup/tab to load

### Version

4.0.0-beta.12

### Additional info

```
"@rainbow-me/rainbowkit": "^2.0.7",
"viem": "^2.10.1",
"wagmi": "^2.8.1"
```

```
"resolutions": {
    "@coinbase/wallet-sdk": "4.0.0-beta.12"
  }
```

### Desktop

- OS: Mac OSX
- Browser: Arc Version 1.41.0 (49440)

**Comment by Yuripetusko** [comment]
I think it might be due to how Arc treats popup more like a new full tabs

**Comment by technophile-04** [comment]
Yup :( It occurs in this too https://coinbase.github.io/coinbase-wallet-sdk/

<details>

<summary>
Demo video : 
</summary>

https://github.com/coinbase/coinbase-wallet-sdk/assets/80153681/a6f5c8db-6bd2-40bc-b296-e2efd66d98e5

</details>


I have also tried with latest dependencies : 

```json
"dependencies": {
  "@rainbow-me/rainbowkit": "2.1.0",
  "viem": "2.10.9",
  "wagmi": "2.9.2",
}
```

Since [wagmi](https://x.com/wevm_dev/status/1791218863545126978) and [raibowkit](https://github.com/rainbow-me/rainbowkit/pull/1964) now directly support v4 but it still doesn't work

**Comment by arjun-dureja** [comment]
Is this still happening on version 4.0.2?

**Comment by Yuripetusko** [comment]
Looks like it's fixed now
