### ISSUE TITLE
Bug: reloadOnDisconnect not working as it should

### ISSUE THREAD

**Issue by Harsh0880** [coinbase/coinbase-wallet-sdk#713]
### Describe the bug

When i disconnect my dapp from coinbase wallet extention, the extension reloads the site even after passing reloadOnDisconnect as false.

### Steps

1. Logged in to my dapp via coinbase wallet extension.
2. After logging in, went to dapp connection in my coinbase wallet extension.
3. Disconnected my dapp from the extension.
4. This causes the site to reload.

### Expected behavior

The site should not reload after getting disconnected from the coinbase wallet extension as i have set  reloadOnDisconnect as false.

### Version

3.5.0

### Desktop

OS: Ubuntu
Browser: Chrome

**Comment by mpeyfuss** [comment]
Have this issue as well. Any updates?

**Comment by Harsh0880** [comment]
> Have this issue as well. Any updates?

No not yet, the issue is in library itself and not resolved.

**Comment by tindt-blockpass** [comment]
The `reloadOnDisconnect` options was not passed to WalletSDKRelay. Therefore, when `resetAndReload` was called, the check to call ui.reload still see it as `true` (default).
For the hotfix, you should add these in your node_modules:

```js
this._relay = new WalletSDKRelay_1.WalletSDKRelay({
    /* other stuff */
    diagnosticLogger: this._diagnosticLogger,
    reloadOnDisconnect: options.reloadOnDisconnect, // add this line
});
```

then use patch-package.

Waiting for coinbase to update it.

**Comment by bangtoven** [comment]
hi. sorry for the belated response. 
we have similar issues reported, so consolidating them into one for proper tracking.
https://github.com/coinbase/coinbase-wallet-sdk/issues/764

**Comment by gimbeljw333** [comment]
I have a similar problem continuing for me as of Feb 6, 2023. My issue is with the Coinbase Wallet chrome browser extension except that I'm not using the coinbase-wallet-sdk. I'm accessing the injected provider just as I would with MetaMask. I wrote custom code that detects all of the events and allows users to switch between MetaMask or Coinbase Wallet extensions. Everything works perfectly except for the onDisconnect event. With MetaMask, disconnecting from the DApp fires the onAccountsChanged, which was surprising that it does not fire the onDisconnect event, but with Coinbase Wallet there doesn't seem to be any events fired. Instead, Coinbase Wallet just keeps reloading the webpage for my DApp. I've tried every test in my code that I can think of and have determined there is nothing wrong with my code except that I cannot detect the onDisconnect event with Coinbase Wallet. I've chosen to post my issue here, because I am unable to find any place to provide feedback on Coinbase Wallet's injected provider feature without using the coinbase-wallet-sdk.

**Comment by cobiliana** [comment]
I was in a situation similar to @gimbeljw333 (using the injected provider instead of using the coinbase sdk) and I managed to fix the reloading by calling disableReloadOnDisconnect as soon as I could upon page load:

`window.coinbaseWalletExtension?.disableReloadOnDisconnect();`
